// ============================================================================
//  DuckUI - single-header Dear ImGui package (Win32 + DirectX 11)
//  by Ducki67  |  https://github.com/Ducki67
//
//  Usage:
//      #include "DuckUI.h"     // that's it - ImGui, backends and all .lib
//                              // linking are handled automatically.
//
//  Bundled Dear ImGui: @IMGUI_VERSION@ (c) Omar Cornut, MIT license
//  (see LICENSE-imgui.txt next to this file).
//
//  THIS FILE IS GENERATED by build.ps1 - do not edit by hand.
//  Build info: @DUCKUI_BUILD_INFO@
// ============================================================================
#pragma once

#define DUCKUI_VERSION "1.0.0"

#if !defined(_MSC_VER)
#error DuckUI requires MSVC or clang-cl (it relies on #pragma comment auto-linking).
#endif
#if !defined(_M_X64)
#error DuckUI ships x64 libraries only - switch your project/platform to x64.
#endif

#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif
#ifndef NOMINMAX
#define NOMINMAX
#endif
#include <windows.h>
#include <d3d11.h>

// ----------------------------------------------------------------------------
// Auto-linking.
//   - Define DUCKUI_NO_AUTOLINK before including to disable all of it.
//   - DUCKUI_LIB_DEBUG / DUCKUI_LIB_RELEASE default to the absolute paths of
//     the libs baked in by build.ps1 (true zero-config). Override them with
//     your own quoted strings before including if you relocate the libs:
//         #define DUCKUI_LIB_RELEASE "DuckUI_x64_Release.lib"  // use LIBPATH
// ----------------------------------------------------------------------------
#ifndef DUCKUI_NO_AUTOLINK
    #pragma comment(lib, "d3d11.lib")
    #pragma comment(lib, "d3dcompiler.lib")
    #ifndef DUCKUI_LIB_DEBUG
    #define DUCKUI_LIB_DEBUG   @DUCKUI_LIB_DEBUG@
    #endif
    #ifndef DUCKUI_LIB_RELEASE
    #define DUCKUI_LIB_RELEASE @DUCKUI_LIB_RELEASE@
    #endif
    #ifdef _DEBUG
    #pragma comment(lib, DUCKUI_LIB_DEBUG)
    #else
    #pragma comment(lib, DUCKUI_LIB_RELEASE)
    #endif
#endif

// imgui_internal.h (bundled below) requires the ImVec2/ImVec4 math operators,
// so they must be enabled before the imgui.h section.
#ifndef IMGUI_DEFINE_MATH_OPERATORS
#define IMGUI_DEFINE_MATH_OPERATORS
#endif
